# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Choice": types.Choice,
    "stream_types.Choice": stream_types.Choice,

    "types.FormattedLLMRequest": types.FormattedLLMRequest,
    "stream_types.FormattedLLMRequest": stream_types.FormattedLLMRequest,

    "types.FormattedMessage": types.FormattedMessage,
    "stream_types.FormattedMessage": stream_types.FormattedMessage,

    "types.ImageContent": types.ImageContent,
    "stream_types.ImageContent": stream_types.ImageContent,

    "types.LLMCompletionRequest": types.LLMCompletionRequest,
    "stream_types.LLMCompletionRequest": stream_types.LLMCompletionRequest,

    "types.LLMCompletionResponse": types.LLMCompletionResponse,
    "stream_types.LLMCompletionResponse": stream_types.LLMCompletionResponse,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.TextContent": types.TextContent,
    "stream_types.TextContent": stream_types.TextContent,

    "types.Tool": types.Tool,
    "stream_types.Tool": stream_types.Tool,

    "types.Usage": types.Usage,
    "stream_types.Usage": stream_types.Usage,


}