# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (11)
# #########################################################################

class Choice(BaseModel):
    index: int
    message: "Message"
    finish_reason: typing.Optional[str] = None

class FormattedLLMRequest(BaseModel):
    conversation: str
    temperature: typing.Optional[float] = None
    max_tokens: typing.Optional[int] = None
    top_p: typing.Optional[float] = None
    top_k: typing.Optional[float] = None
    seed: typing.Optional[int] = None
    stop: typing.Optional[typing.List[str]] = None

class FormattedMessage(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['system'], typing_extensions.Literal['assistant'], typing_extensions.Literal['tool']]
    content: str

class ImageContent(BaseModel):
    type: str
    image_url: typing.Dict[str, str]
    cache_control: typing.Optional[typing.Dict[str, str]] = None

class LLMCompletionRequest(BaseModel):
    messages: typing.List["Message"]
    tools: typing.Optional[typing.List["Tool"]] = None
    temperature: typing.Optional[float] = None
    max_tokens: typing.Optional[int] = None
    top_p: typing.Optional[float] = None
    top_k: typing.Optional[float] = None
    seed: typing.Optional[int] = None
    stop: typing.Optional[typing.List[str]] = None

class LLMCompletionResponse(BaseModel):
    id: str
    choices: typing.List["Choice"]
    usage: typing.Optional["Usage"] = None
    model: typing.Optional[str] = None
    created: typing.Optional[int] = None

class Message(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['system'], typing_extensions.Literal['assistant'], typing_extensions.Literal['tool']]
    content: typing.List[typing.Union["TextContent", "ImageContent"]]
    tool_calls: typing.Optional[typing.List[typing.Dict[str, str]]] = None
    tool_call_id: typing.Optional[str] = None
    name: typing.Optional[str] = None

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class TextContent(BaseModel):
    type: str
    text: str
    cache_control: typing.Optional[typing.Dict[str, str]] = None

class Tool(BaseModel):
    type: str
    function_def: typing.Dict[str, str]

class Usage(BaseModel):
    prompt_tokens: typing.Optional[int] = None
    completion_tokens: typing.Optional[int] = None
    total_tokens: typing.Optional[int] = None
    prompt_tokens_details: typing.Optional[typing.Dict[str, str]] = None

# #########################################################################
# Generated type aliases (1)
# #########################################################################


Content: typing_extensions.TypeAlias = typing.Union["TextContent", "ImageContent"]
