# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class FormattedLLMRequest(BaseModel):
    conversation: typing.Optional[str] = None
    temperature: typing.Optional[float] = None
    max_tokens: typing.Optional[int] = None
    top_p: typing.Optional[float] = None
    top_k: typing.Optional[float] = None
    seed: typing.Optional[int] = None
    stop: typing.Optional[typing.List[str]] = None

class FormattedMessage(BaseModel):
    role: typing.Optional[typing.Union[str, str, str, str]] = None
    content: typing.Optional[str] = None

class LLMCompletionResponse(BaseModel):
    content: typing.Optional[str] = None
    tool_calls: typing.Optional[typing.Dict[str, str]] = None
    prompt_tokens: typing.Optional[int] = None
    completion_tokens: typing.Optional[int] = None
    total_tokens: typing.Optional[int] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
