# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.FormattedLLMRequest": types.FormattedLLMRequest,
    "stream_types.FormattedLLMRequest": stream_types.FormattedLLMRequest,

    "types.FormattedMessage": types.FormattedMessage,
    "stream_types.FormattedMessage": stream_types.FormattedMessage,

    "types.LLMCompletionResponse": types.LLMCompletionResponse,
    "stream_types.LLMCompletionResponse": stream_types.LLMCompletionResponse,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,


}